#!/usr/bin/env python3
"""Aggregate P15 Phase 1/2/3 summaries into 4 LaTeX tables for paper §VII."""
from __future__ import annotations

import json
import math
import statistics
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TABLES_DIR = ROOT / "tetrarl" / "eval" / "tables"
TABLES_DIR.mkdir(parents=True, exist_ok=True)

PHASE3_RUNS = Path("/Users/zexinli/Downloads/TetraRL-p15-phase3/runs/p15_phase3_orin_agx_atari")

PHASES = [
    {"n": 1, "label": "CartPole $\\times$ Orin AGX", "runs": ROOT / "runs" / "p15_phase1_orin_agx_cartpole"},
    {"n": 2, "label": "CartPole $\\times$ Orin Nano", "runs": ROOT / "runs" / "p15_phase2_orin_nano_cartpole"},
    {"n": 3, "label": "Atari Breakout $\\times$ Orin AGX", "runs": PHASE3_RUNS},
]

ALGOS = ["dqn", "ddqn", "c51", "a2c", "ppo"]
WRAPPERS = ["maxa", "maxp", "r3", "duojoule", "tetrarl"]
WRAPPER_LABEL = {"maxa": "MAX-A", "maxp": "MAX-P", "r3": "R$^3$", "duojoule": "DuoJoule", "tetrarl": "\\textbf{TetraRL}"}
ALGO_LABEL = {"dqn": "DQN", "ddqn": "DDQN", "c51": "C51", "a2c": "A2C", "ppo": "PPO"}


def _final_reward(curve):
    if not curve:
        return float("nan")
    tail = curve[-10:] if len(curve) >= 10 else curve
    return float(statistics.fmean(tail))


def _mean_std(values):
    clean = [v for v in values if v is not None and not (isinstance(v, float) and math.isnan(v))]
    if not clean:
        return float("nan"), float("nan")
    if len(clean) == 1:
        return float(clean[0]), 0.0
    return float(statistics.fmean(clean)), float(statistics.pstdev(clean))


def load_phase(phase):
    runs_dir = phase["runs"]
    cells = {}
    if not runs_dir.is_dir():
        print(f"WARN: phase {phase['n']} runs dir missing: {runs_dir}")
        return cells
    for sub in sorted(runs_dir.iterdir()):
        if not sub.is_dir() or sub.name.startswith("_"):
            continue
        sj = sub / "summary.json"
        if not sj.is_file():
            continue
        try:
            d = json.loads(sj.read_text())
        except Exception as e:
            print(f"WARN: parse {sj}: {e}")
            continue
        algo = d.get("algo", "")
        wrapper = d.get("wrapper", "")
        key = (algo, wrapper)
        bucket = cells.setdefault(key, {"completed": [], "skipped": False, "reason": ""})
        status = d.get("status", "")
        if status == "COMPLETED":
            bucket["completed"].append(d)
        elif status == "SKIPPED":
            bucket["skipped"] = True
            bucket["reason"] = d.get("reason", bucket["reason"])
    return cells


def aggregate_cell(seed_dicts):
    metrics = {}
    for m in ("framework_overhead_pct", "mean_p99_step_ms", "mean_energy_j", "peak_gpu_memory_mb"):
        vals = [d.get(m) for d in seed_dicts if d.get(m) is not None]
        metrics[m] = _mean_std(vals)
    rewards = [_final_reward(d.get("cumulative_reward_curve")) for d in seed_dicts]
    metrics["final_reward"] = _mean_std(rewards)
    return metrics


def fmt_ms(mean, std):
    return "n/a" if math.isnan(mean) else f"{mean:.3f} $\\pm$ {std:.3f}"
def fmt_pct(mean, std):
    return "n/a" if math.isnan(mean) else f"{mean:.2f} $\\pm$ {std:.2f}"
def fmt_energy(mean, std):
    return "n/a" if math.isnan(mean) else f"{mean*1000:.3f} $\\pm$ {std*1000:.3f}"
def fmt_mem(mean, std):
    return "n/a" if math.isnan(mean) else f"{mean:.2f} $\\pm$ {std:.2f}"
def fmt_reward(mean, std):
    return "n/a" if math.isnan(mean) else f"{mean:.2f} $\\pm$ {std:.2f}"


def write_phase_table(phase, cells):
    out = TABLES_DIR / f"p15_phase{phase['n']}_table.tex"
    n = phase["n"]
    label = phase["label"]
    L = []
    L.append(r"% Auto-generated by scripts/p15_aggregate_all.py — do not edit by hand.")
    L.append(r"\begin{table*}[!t]")
    L.append(r"\centering")
    L.append(
        f"\\caption{{P15 Phase {n} on-device DRL head-to-head matrix: {label}. "
        f"21 active (algo, wrapper) cells $\\times$ 3 seeds $=$ 63 COMPLETED $+$ 12 SKIPPED "
        f"(R$^3$/DuoJoule incompatible with A2C/PPO). Per cell shows mean $\\pm$ std over 3 seeds. "
        f"Energy is per-step (mJ); peak memory is GPU peak via "
        f"\\texttt{{torch.cuda.max\\_memory\\_allocated}} (CartPole on Orin reads 0\\,MB because the "
        f"MLP runs CPU-only; Atari CNN allocates real GPU memory). "
        f"Final reward $=$ mean of last 10 episodes' returns.}}"
    )
    L.append(f"\\label{{tab:p15_phase{n}}}")
    L.append(r"\renewcommand{\arraystretch}{1.05}")
    L.append(r"\scriptsize")
    L.append(r"\setlength{\tabcolsep}{3pt}")
    L.append(r"\begin{tabular}{llrrrrr}")
    L.append(r"\toprule")
    L.append(r"Algo & Wrapper & Overhead (\%) & p99 step (ms) & Energy/step (mJ) & Peak GPU (MB) & Final reward \\")
    L.append(r"\midrule")
    for algo in ALGOS:
        for wrapper in WRAPPERS:
            cell = cells.get((algo, wrapper))
            if cell is None:
                L.append(f"{ALGO_LABEL[algo]} & {WRAPPER_LABEL[wrapper]} & \\multicolumn{{5}}{{c}}{{\\emph{{(no data)}}}} \\\\")
                continue
            if cell["skipped"] and not cell["completed"]:
                L.append(f"{ALGO_LABEL[algo]} & {WRAPPER_LABEL[wrapper]} & \\multicolumn{{5}}{{c}}{{\\emph{{SKIPPED (incompatible)}}}} \\\\")
                continue
            agg = aggregate_cell(cell["completed"])
            L.append(
                f"{ALGO_LABEL[algo]} & {WRAPPER_LABEL[wrapper]} & "
                f"{fmt_pct(*agg['framework_overhead_pct'])} & {fmt_ms(*agg['mean_p99_step_ms'])} & "
                f"{fmt_energy(*agg['mean_energy_j'])} & {fmt_mem(*agg['peak_gpu_memory_mb'])} & "
                f"{fmt_reward(*agg['final_reward'])} \\\\"
            )
        if algo != ALGOS[-1]:
            L.append(r"\midrule")
    L.append(r"\bottomrule")
    L.append(r"\end{tabular}")
    L.append(r"\end{table*}")
    L.append("")
    out.write_text("\n".join(L))
    print(f"OK: wrote {out}")


def write_cross_platform_table(p1_cells, p2_cells):
    out = TABLES_DIR / "p15_cross_platform_table.tex"
    L = []
    L.append(r"% Auto-generated by scripts/p15_aggregate_all.py — do not edit by hand.")
    L.append(r"\begin{table}[!t]")
    L.append(r"\centering")
    L.append(
        r"\caption{P15 cross-platform: per-step p99 latency on Orin AGX (Phase 1) vs.\ Orin Nano "
        r"(Phase 2), CartPole-v1, mean over 3 seeds. Ratio column $=$ Nano $/$ AGX (a value $>1$ "
        r"means Nano is slower per step).}"
    )
    L.append(r"\label{tab:p15_cross_platform}")
    L.append(r"\renewcommand{\arraystretch}{1.05}")
    L.append(r"\scriptsize")
    L.append(r"\setlength{\tabcolsep}{3pt}")
    L.append(r"\begin{tabular}{llrrr}")
    L.append(r"\toprule")
    L.append(r"Algo & Wrapper & p99 AGX (ms) & p99 Nano (ms) & Nano/AGX \\")
    L.append(r"\midrule")
    for algo in ALGOS:
        for wrapper in WRAPPERS:
            c1 = p1_cells.get((algo, wrapper))
            c2 = p2_cells.get((algo, wrapper))
            if c1 is None or c2 is None or not c1.get("completed") or not c2.get("completed"):
                continue
            a1 = aggregate_cell(c1["completed"])
            a2 = aggregate_cell(c2["completed"])
            m1, _ = a1["mean_p99_step_ms"]
            m2, _ = a2["mean_p99_step_ms"]
            if math.isnan(m1) or math.isnan(m2) or m1 <= 0:
                continue
            ratio = m2 / m1
            L.append(f"{ALGO_LABEL[algo]} & {WRAPPER_LABEL[wrapper]} & {m1:.3f} & {m2:.3f} & {ratio:.2f}$\\times$ \\\\")
        if algo != ALGOS[-1]:
            L.append(r"\midrule")
    L.append(r"\bottomrule")
    L.append(r"\end{tabular}")
    L.append(r"\end{table}")
    L.append("")
    out.write_text("\n".join(L))
    print(f"OK: wrote {out}")


def main():
    cells_by_phase = {}
    for phase in PHASES:
        cells = load_phase(phase)
        cells_by_phase[phase["n"]] = cells
        n_complete = sum(len(c["completed"]) for c in cells.values())
        n_skipped = sum(1 for c in cells.values() if c["skipped"] and not c["completed"])
        print(f"Phase {phase['n']}: {len(cells)} (algo,wrapper) cells, {n_complete} COMPLETED rows, {n_skipped} SKIPPED pairs")
        write_phase_table(phase, cells)
    write_cross_platform_table(cells_by_phase[1], cells_by_phase[2])


if __name__ == "__main__":
    main()
